<a href="https://colab.research.google.com/github/deepan98raj-dotcom/All_concept_Assignment/blob/main/All_Concepts_assignment_1_on_28_08_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using In build datatypes like List , Tuples and Dictionary. Build a Small Logic of any business model of yout choice with Operators,Conditionals involved.




```
LIST []- It allows duplicate values
       - It is mutable values
       - It is Ordered
       - It can be add,Remove,replace
```

In [ ]:
name = ['Deepan','diana','ram','ravi','nisha','sibiraj','yogi',3,3.35,True,{3:4},'ravi']

print(name)
print(len(name))
print(name[4])
print(type(name))

# ADD
name.append(1)
print(name)

# REMOVE
name.remove(name[5])
print(name)

# REPLACE
name[3] = 'gopal'
print(name)



['Deepan', 'diana', 'ram', 'ravi', 'nisha', 'sibiraj', 'yogi', 3, 3.35, True, {3: 4}, 'ravi']
12
nisha
<class 'list'>
['Deepan', 'diana', 'ram', 'ravi', 'nisha', 'sibiraj', 'yogi', 3, 3.35, True, {3: 4}, 'ravi', 1]
['Deepan', 'diana', 'ram', 'ravi', 'nisha', 'yogi', 3, 3.35, True, {3: 4}, 'ravi', 1]
['Deepan', 'diana', 'ram', 'gopal', 'nisha', 'yogi', 3, 3.35, True, {3: 4}, 'ravi', 1]




```
Tuple ()- It is order
        - It is unmutable
        - it can't be add,remove & replace
        - It allow the duplicate
```



In [ ]:
tup = ('Deepan','diana','ram','ravi','nisha','sibiraj','yogi',3,3.35,True,{3:4},'ravi')

print(tup)
print(len(tup))
print(tup[2])
print(type(tup))

# It can display the output using index values
print(tup[2:5])
print(tup[-5:-3])


('Deepan', 'diana', 'ram', 'ravi', 'nisha', 'sibiraj', 'yogi', 3, 3.35, True, {3: 4}, 'ravi')
12
ram
<class 'tuple'>
('ram', 'ravi', 'nisha')
(3, 3.35)



```
SET {}  - It remove the duplicate
        - It is unorder
        - it can be add,remove & replace
```

In [ ]:
setname = {'Deepan','diana','ram','ravi','nisha','sibiraj','yogi',3,3.35,True,'ravi','Deepan','diana','ram','ravi'}

print(setname)
print(type(setname))

# ADD
setname.add('mani')
print(setname)

# REMOVE
setname.remove('yogi')
print(setname)


{True, 3.35, 3, 'Deepan', 'ram', 'ravi', 'diana', 'sibiraj', 'nisha', 'yogi'}
<class 'set'>
{True, 3.35, 3, 'Deepan', 'ram', 'ravi', 'diana', 'sibiraj', 'mani', 'nisha', 'yogi'}
{True, 3.35, 3, 'Deepan', 'ram', 'ravi', 'diana', 'sibiraj', 'mani', 'nisha'}


```
Dictionary - It paired as key & value
           - It enclosed with {}
           - key is fixed & value is change
```


In [ ]:
diction = { 'Name' : 'Deepan', 'age' : 28, 'location' : 'chennai', 'couse' : 'GEN AI'}

print(diction)
print(type(diction))
print(len(diction))
print(diction['age'])
print(diction.get('Name'))


# Acess the value & change
diction['location'] = 'banglore'
print(diction)




{'Name': 'Deepan', 'age': 28, 'location': 'chennai', 'couse': 'GEN AI'}
<class 'dict'>
4
28
Deepan
{'Name': 'Deepan', 'age': 28, 'location': 'banglore', 'couse': 'GEN AI'}


# Build a Logic for any Business model using with Classes (OOPS) involved .

In [ ]:
# Using string formatting

all_info = {'Name' : 'Deepan',
            'age' : 28,
            'location' : 'chennai',
            'course' : 'GEN AI'}

print('I am %(Name)s ,My Age is %(age)d Located in %(location)s Study %(course)s Course' % all_info)

print('I am {} ,My Age is {} Located in {} Study {} Course'.format(all_info['Name'],all_info['age'],all_info['location'],all_info['course']))

print('I am {Name} ,My Age is {age} Located in {location} Study {course} Course'.format(**all_info))

print(f"I am {all_info['Name']}, My Age is {all_info['age']} Located in {all_info['location']} Study {all_info['course']} Course")

I am Deepan ,My Age is 28 Located in chennai Study GEN AI Course
I am Deepan ,My Age is 28 Located in chennai Study GEN AI Course
I am Deepan ,My Age is 28 Located in chennai Study GEN AI Course
I am Deepan, My Age is 28 Located in chennai Study GEN AI Course


# Enlist all the Numpy Functions you studied one by one and Incorporate those concepts in a Project .Include Numpy Broadcasting and  hypothesis testing np.mean,median,mode,std


### NumPy
 Its used for scientific and numerical value , Dimensional array , matrix , algebia , random number

 It Open Source in python

In [ ]:
# ARRAY

num = [1,2,3,4,5,6,7,8,9]
print(num)
print(type(num))

mynum = np.array(num)
print(mynum)
print(type(mynum))


[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
# MATRIX

no = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print(no)
myno = np.array(no)
print(myno)
print(type(myno))

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [ ]:
# RANDOM

randomfloat = np.random.rand(5,5)
print(randomfloat)

randomnormal = np.random.randn(12)
print(randomnormal)

randomint = np.random.randint(1,50,size=(4,4))
print(randomint)

randomintshape = np.random.randint(1,50,size=(4,4))
print(randomintshape.shape)

[[0.54887173 0.52161759 0.49120696 0.64649345 0.14523977]
 [0.02367124 0.99535881 0.51171402 0.64850108 0.67666291]
 [0.71584275 0.12486933 0.4736503  0.99034913 0.30712911]
 [0.86945437 0.89362437 0.49345693 0.1359053  0.88225712]
 [0.24496551 0.85654766 0.74302555 0.67597617 0.75186387]]
[-0.58428271 -1.91155277 -0.50372056 -0.50056187  0.20009266  0.60627249
  0.64655583 -1.63959893 -0.89209852  0.48560408  0.85328236 -0.50128339]
[[12 14 45 44]
 [15 26 11 30]
 [48 25 11 17]
 [36 40 46 47]]
(4, 4)


In [ ]:
# RANGE

range = np.arange(1,10)
print(range)

range = np.arange(1,10,2)
print(range)


[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
# LINSPACE

my_linspace = np.linspace(1,50,20)
print(my_linspace)

[ 1.          3.57894737  6.15789474  8.73684211 11.31578947 13.89473684
 16.47368421 19.05263158 21.63157895 24.21052632 26.78947368 29.36842105
 31.94736842 34.52631579 37.10526316 39.68421053 42.26315789 44.84210526
 47.42105263 50.        ]


# Enlist all the Pandas Functions you studied one by one and Incorporate those concepts in a Project .

### Pandas
    pandas is read the data from the output source library which is open source that import file through CSV,Excel,JSON, etc...

    - load the data
    - cleaning the data & find the missing values
    - Data preprocessing the file
    - Data visualization using seaborn & matplot

It preforms 1D series and 2D dataframe efficiently work with struture data


# Project One:

In [ ]:
import pandas as pd
import numpy as np


df = pd.read_csv('/content/data.csv')
print(df)
print(df.shape)
print(df.columns)


    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [ ]:
print(df.head(10))
print(df.tail(15))

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0
5        60  '2020/12/06'    102       127     300.0
6        60  '2020/12/07'    110       136     374.0
7       450  '2020/12/08'    104       134     253.3
8        30  '2020/12/09'    109       133     195.1
9        60  '2020/12/10'     98       124     269.0
    Duration          Date  Pulse  Maxpulse  Calories
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130      

In [ ]:
print(df.describe)
print(df.info())

<bound method NDFrame.describe of     Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     

In [ ]:
df.isna().sum()

,0
Duration,0
Date,1
Pulse,0
Maxpulse,0
Calories,2


In [ ]:
df['Date'].unique()

array(["'2020/12/01'", "'2020/12/02'", "'2020/12/03'", "'2020/12/04'",
       "'2020/12/05'", "'2020/12/06'", "'2020/12/07'", "'2020/12/08'",
       "'2020/12/09'", "'2020/12/10'", "'2020/12/11'", "'2020/12/12'",
       "'2020/12/13'", "'2020/12/14'", "'2020/12/15'", "'2020/12/16'",
       "'2020/12/17'", "'2020/12/18'", "'2020/12/19'", "'2020/12/20'",
       "'2020/12/21'", nan, "'2020/12/23'", "'2020/12/24'",
       "'2020/12/25'", '20201226', "'2020/12/27'", "'2020/12/28'",
       "'2020/12/29'", "'2020/12/30'", "'2020/12/31'"], dtype=object)

In [ ]:
mean_value = df['Calories'].mean()
df['Calories'] = df['Calories'].fillna(mean_value)
df.isna().sum()

,0
Duration,0
Date,1
Pulse,0
Maxpulse,0
Calories,0


In [ ]:
df['Date'].fillna("'2020/12/22'", inplace=True)

/tmp/ipykernel_1601/1243348254.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Date'].fillna("'2020/12/22'", inplace=True)


In [ ]:
df.isna().sum()

,0
Duration,0
Date,0
Pulse,0
Maxpulse,0
Calories,0


In [ ]:
df['Date'].unique()

array(["'2020/12/01'", "'2020/12/02'", "'2020/12/03'", "'2020/12/04'",
       "'2020/12/05'", "'2020/12/06'", "'2020/12/07'", "'2020/12/08'",
       "'2020/12/09'", "'2020/12/10'", "'2020/12/11'", "'2020/12/12'",
       "'2020/12/13'", "'2020/12/14'", "'2020/12/15'", "'2020/12/16'",
       "'2020/12/17'", "'2020/12/18'", "'2020/12/19'", "'2020/12/20'",
       "'2020/12/21'", "'2020/12/22'", "'2020/12/23'", "'2020/12/24'",
       "'2020/12/25'", '20201226', "'2020/12/27'", "'2020/12/28'",
       "'2020/12/29'", "'2020/12/30'", "'2020/12/31'"], dtype=object)

In [ ]:

df['date_adjust'] = df['Date'].astype(str).replace('20201226', '2020/12/26')

df['date_adjust'] = df['date_adjust'].str.replace("'", "")

df['Date_new'] = pd.to_datetime(df['date_adjust'], infer_datetime_format=True)
print(df)

    Duration          Date  Pulse  Maxpulse  Calories date_adjust   Date_new
0         60  '2020/12/01'    110       130    409.10  2020/12/01 2020-12-01
1         60  '2020/12/02'    117       145    479.00  2020/12/02 2020-12-02
2         60  '2020/12/03'    103       135    340.00  2020/12/03 2020-12-03
3         45  '2020/12/04'    109       175    282.40  2020/12/04 2020-12-04
4         45  '2020/12/05'    117       148    406.00  2020/12/05 2020-12-05
5         60  '2020/12/06'    102       127    300.00  2020/12/06 2020-12-06
6         60  '2020/12/07'    110       136    374.00  2020/12/07 2020-12-07
7        450  '2020/12/08'    104       134    253.30  2020/12/08 2020-12-08
8         30  '2020/12/09'    109       133    195.10  2020/12/09 2020-12-09
9         60  '2020/12/10'     98       124    269.00  2020/12/10 2020-12-10
10        60  '2020/12/11'    103       147    329.30  2020/12/11 2020-12-11
11        60  '2020/12/12'    100       120    250.70  2020/12/12 2020-12-12

/tmp/ipykernel_1601/1014984393.py:5: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['Date_new'] = pd.to_datetime(df['date_adjust'], infer_datetime_format=True)
