<a href="https://colab.research.google.com/github/deepan98raj-dotcom/All_concept_Assignment/blob/main/All_Concepts_assignment_2_on_28_08_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project One : Movie Recommendation Engine

 What you will do: Create a 2D array where rows represent users and columns represent movies. Fill the matrix with ratings (1–5) and use 0 for unwatched movies.


Imagine this type of movie review
```
| User   | Movie 1 | Movie 2 | Movie 3 | Movie 4 | Movie 5 |
| ------ | ------: | ------: | ------: | ------: | ------: |
| User 1 |       5 |       0 |       3 |       4 |       0 |
| User 2 |       4 |       2 |       0 |       5 |       3 |
| User 3 |       0 |       5 |       4 |       0 |       2 |
| User 4 |       3 |       0 |       5 |       2 |       4 |
```

In [ ]:
import numpy as np


# Create the 2D array (Rows: Users, Columns: Movies)

# Modified rating_matrix to include more rows (users) to prevent IndexError


ratings = np.array([ #User1, #User2, #User3, #User4
    [5, 0, 3, 4, 0],
    [4, 2, 0, 5, 3],
    [0, 5, 4, 0, 2],
    [3, 0, 5, 2, 4]
])

print(ratings)



[[5 0 3 4 0]
 [4 2 0 5 3]
 [0 5 4 0 2]
 [3 0 5 2 4]]


In [ ]:
ratings[0]

array([5, 0, 3, 4, 0])

In [ ]:
ratings[0][3]

np.int64(4)

Core NumPy skills: Matrix multiplication (np.dot), calculating Euclidean distance or cosine similarity, and sorting array indices (np.argsort).

###**Define**

np.dot() → calculate relationships between vectors

Euclidean distance → find users who are close/similar

Cosine similarity → measure similarity between users/movies

np.argsort() → rank the most similar users/movies

In [ ]:
# dot

A = np.array([[1,3],[2,4]])

B = np.array([[5,2],[1,2]])

result=np.dot(A,B)
print(result)

# Euclidean distance
user1 = np.array([5, 0, 3, 4, 0])
user2 = np.array([1, 2, 3, 3, 5])

distance = np.linalg.norm(user1 - user2)
print(distance)

# Cosine similarity
use1 = np.array([5, 4, 3])
use2 = np.array([4, 2, 3])

cosine_similarity = np.dot(use1, use2) / (np.linalg.norm(use1) * np.linalg.norm(use2))

print(cosine_similarity)

# argSorting
arr = np.array([3,2,1])
sorted_indices = np.argsort(arr)
print(sorted_indices)



[[ 8  8]
 [14 12]]
6.782329983125268
0.9716676031619469
[2 1 0]


In [ ]:
import numpy as np

# Movie names
movies = np.array([
    "Avatar",
    "Titanic",
    "Inception",
    "Avengers",
    "Interstellar",
    "Joker"
])

ratings = np.array([
    [5, 4, 0, 5, 0, 3],  # User 0
    [5, 0, 4, 5, 3, 0],  # User 1
    [1, 2, 5, 0, 4, 0],  # User 2
    [4, 5, 0, 4, 0, 3]   # User 3
])


def cosine_similarity(a, b):
    denominator = np.linalg.norm(a) * np.linalg.norm(b)

    if denominator == 0:
        return 0

    return np.dot(a, b) / denominator


# Input user
user_id = int(input("Enter User ID: "))

target_user = ratings[user_id]

# Calculate similarity
similarities = []

for i in range(len(ratings)):

    if i == user_id:
        continue

    similarity = cosine_similarity(
        target_user,
        ratings[i]
    )

    similarities.append((i, similarity))


# Sort users by similarity
similarities.sort(
    key=lambda x: x[1],
    reverse=True
)

print("\nSimilar users:")
for user, score in similarities:
    print("User", user, "Similarity:", round(score, 2))


# Calculate recommendation scores
recommendation_scores = np.zeros(len(movies))

for similar_user, similarity in similarities:

    for movie_index in range(len(movies)):

        # Only consider movies not watched
        if target_user[movie_index] == 0:

            recommendation_scores[movie_index] += (
                similarity *
                ratings[similar_user][movie_index]
            )


# Sort movie indices by recommendation score
ranked_movies = np.argsort(
    recommendation_scores
)[::-1]


# Get top 3 unwatched movies
recommendations = []

for movie_index in ranked_movies:

    if target_user[movie_index] == 0:

        recommendations.append(movie_index)

    if len(recommendations) == 3:
        break


print("\nTop 3 Recommended Movies:")

for movie_index in recommendations:

    print(
        movies[movie_index],
        "Score:",
        round(recommendation_scores[movie_index], 2)
    )

Enter User ID: 1

Similar users:
User 0 Similarity: 0.67
User 2 Similarity: 0.63
User 3 Similarity: 0.57

Top 3 Recommended Movies:
Titanic Score: 6.77
Joker Score: 3.71


# Weather Station Analytics

Analyze a year's worth of climate data using structured numerical arrays.

What you will do: Generate a synthetic dataset or read a text file containing daily weather data (Temperature, Rainfall, Wind Speed).


In [ ]:


np.random.seed(42)

days = 30

temperature = np.random.uniform(25, 38, days)
rainfall = np.random.uniform(0, 25, days)
wind_speed = np.random.uniform(5, 30, days)

weather = np.column_stack(
    (temperature, rainfall, wind_speed)
)

print(weather)

[[29.86902155 15.1886213  14.71693224]
 [37.35928598  4.26310309 11.78372579]
 [34.51592124  1.62628982 25.71843773]
 [32.78256029 23.72213843 13.91883317]
 [27.02824233 24.14080083 12.02336274]
 [27.02792876 20.2099337  18.56740208]
 [25.75508696  7.61534423  8.52310562]
 [36.2602899   2.44180285 25.05492452]
 [32.81449515 17.10582566  6.86376609]
 [34.20494351 11.00381234 29.67217342]
 [25.26759843  3.05095587 24.30611923]
 [37.60882808 12.37942275  9.96789204]
 [35.82175433  0.85971303  5.13805293]
 [27.76040844 22.73301005 25.38653571]
 [27.36372457  6.46949954 22.6714336 ]
 [27.38425863 16.56305711 23.2251792 ]
 [28.95514916  7.7927769  24.28175867]
 [31.82183361 13.00170053  6.85111629]
 [30.61528524 13.66775698 13.96164321]
 [28.78597882  4.62136139  7.89672649]
 [32.95408763 24.23961569 26.57758565]
 [26.81342019 19.37832058 20.58245317]
 [28.79788043 23.48747354 13.27245062]
 [29.76270396 22.37068376  6.58895876]
 [30.92890979 14.94749947 12.77455804]
 [35.2072875  23.04685588

In [ ]:
# Core NumPy skills: Statistical functions (np.mean, np.std, np.min, np.max)

marks = np.array([60, 70, 80, 90, 100])

print(np.mean(marks)) # mid value
print(np.std(marks))  # average value
print(np.min(marks))  # min value
print(np.max(marks))  # max value


80.0
14.142135623730951
60
100


In [ ]:
# axis-specific operations (axis=0 vs axis=1)

data = np.array([ [10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

print(np.mean(data, axis=0))
print(np.mean(data, axis=1))


[40. 50. 60.]
[20. 50. 80.]


In [ ]:
# Boolean array

marks = np.array([60,70,80,90,100])

result = marks[marks > 60]
print(result)

output = marks > 60
print(output)


[ 70  80  90 100]
[False  True  True  True  True]


In [ ]:
# Weather data

days = np.array(['jan-01','jan-02','jan-03','jan-04','jan-05','jan-06','jan-07','jan-08','jan-09','jan-10'])

temperature = np.array([25,28,27,26,29,30,35,29,26,31])

rainfall = np.array([2, 0, 15, 5, 0,
                     20, 3, 0, 12, 25])

average_temperature = np.mean(temperature)
print('Average Temperature:', average_temperature)

threshold = 10

rain_mask = rainfall > threshold

print('\n Boolean Array:')
print(rain_mask)

hot_days = days[temperature > 30]
print('\nHot Days:')
print(hot_days)

print('\n Days with rainfall above', threshold, 'mm:')
print(days[rain_mask])

print(days[rain_mask])

print('\n Rainfall values:')
print(rainfall[rain_mask])

min_temp = np.min(temperature)
max_temp = np.max(temperature)

normalized_temperature = ((temperature - min_temp) / (max_temp - min_temp))
print('\n Minimum Temperature:', min_temp)
print('Maximum Temperature:', max_temp)



Average Temperature: 28.6

 Boolean Array:
[False False  True False False  True False False  True  True]

Hot Days:
['jan-07' 'jan-10']

 Days with rainfall above 10 mm:
['jan-03' 'jan-06' 'jan-09' 'jan-10']
['jan-03' 'jan-06' 'jan-09' 'jan-10']

 Rainfall values:
[15 20 12 25]

 Minimum Temperature: 25
Maximum Temperature: 35


#  Student Marks Analysis & Gradebook
Build an automated grading script using basic classroom data. You can create a mock dataset using Python dictionaries and convert it directly into a DataFrame.


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

students = {
    'student':['arun','sai','priya','rahul','sneha'],
    'math':[85,72,67,89,92],
    'science':[90,78,88,75,82],
    'history':[95,75,92,65,70]
}

df = pd.DataFrame(students)
print(df.head())
df['Total'] = df[['math','science','history']].sum(axis=1)

df['Average'] = df[['math','science','history']].mean(axis=1)

def cal_grade(avg):
  if avg >= 90:
    return 'A+'
  elif avg >= 80:
    return 'A'
  elif avg >= 70:
    return 'B'
  elif avg >= 60:
    return 'C'
  elif avg >= 50:
    return 'D'
  else:
    return 'F'

df['Grade'] = df['Average'].apply(cal_grade)
df['Average'] = df['Average'].round(2)

df = df.sort_values('Average',ascending=False)

print('STUDENT GRADEBOOK')
print(df)

print('\n Top Student:',df.iloc[0]['student'])

print('\n Students with A grade or above:')
print(df[df['Grade'] >= '80'])

  student  math  science  history
0    arun    85       90       95
1     sai    72       78       75
2   priya    67       88       92
3   rahul    89       75       65
4   sneha    92       82       70
STUDENT GRADEBOOK
  student  math  science  history  Total  Average Grade
0    arun    85       90       95    270    90.00    A+
2   priya    67       88       92    247    82.33     A
4   sneha    92       82       70    244    81.33     A
3   rahul    89       75       65    229    76.33     B
1     sai    72       78       75    225    75.00     B

 Top Student: arun

 Students with A grade or above:
  student  math  science  history  Total  Average Grade
0    arun    85       90       95    270    90.00    A+
2   priya    67       88       92    247    82.33     A
4   sneha    92       82       70    244    81.33     A
3   rahul    89       75       65    229    76.33     B
1     sai    72       78       75    225    75.00     B


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv('/content/retail_sales_dataset.csv')
print(dataset)


     Transaction ID        Date Customer ID  Gender  Age Product Category  \
0                 1  2023-11-24     CUST001    Male   34           Beauty   
1                 2  2023-02-27     CUST002  Female   26         Clothing   
2                 3  2023-01-13     CUST003    Male   50      Electronics   
3                 4  2023-05-21     CUST004    Male   37         Clothing   
4                 5  2023-05-06     CUST005    Male   30           Beauty   
..              ...         ...         ...     ...  ...              ...   
995             996  2023-05-16     CUST996    Male   62         Clothing   
996             997  2023-11-17     CUST997    Male   52           Beauty   
997             998  2023-10-29     CUST998  Female   23           Beauty   
998             999  2023-12-05     CUST999  Female   36      Electronics   
999            1000  2023-04-12    CUST1000    Male   47      Electronics   

     Quantity  Price per Unit  Total Amount  
0           3              50

In [ ]:
# Group by 'Product Category' to calculate total units sold and average prices
category_sales = dataset.groupby('Product Category').agg(
    total_units_sold=('Quantity', 'sum'),
    average_price=('Price per Unit', 'mean'),
    total_grossing=('Total Amount', 'sum')
)

# Sort the results by 'total_grossing' to find the highest-grossing products
top_5_grossing = category_sales.sort_values(by='total_grossing', ascending=False).head(5)

print("Top 5 Highest-Grossing Product Categories:")
print(top_5_grossing)

Top 5 Highest-Grossing Product Categories:
                  total_units_sold  average_price  total_grossing
Product Category                                                 
Electronics                    849     181.900585          156905
Clothing                       894     174.287749          155580
Beauty                         771     184.055375          143515


### Top 5 Transactions by Total Amount

In [ ]:
top_5_transactions = dataset.sort_values(by='Total Amount', ascending=False).head(5)
display(top_5_transactions)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
945,946,2023-05-08,CUST946,Male,62,Electronics,4,500,2000
71,72,2023-05-23,CUST072,Female,20,Electronics,4,500,2000
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000
576,577,2023-02-13,CUST577,Male,21,Beauty,4,500,2000
571,572,2023-04-20,CUST572,Male,31,Clothing,4,500,2000


In [ ]:

# This sums all numerical columns for the entire DataFrame, which might not be what's intended without a groupby
print(dataset.sum(numeric_only=True))

Transaction ID    500500
Age                41392
Quantity            2514
Price per Unit    179890
Total Amount      456000
dtype: int64


In [ ]:
# Fixed: Corrected column name from 'Total_Sales' to 'Total Amount'
print(dataset.sort_values('Total Amount',ascending=False))

     Transaction ID        Date Customer ID  Gender  Age Product Category  \
945             946  2023-05-08     CUST946    Male   62      Electronics   
71               72  2023-05-23     CUST072  Female   20      Electronics   
14               15  2023-01-16     CUST015  Female   42      Electronics   
576             577  2023-02-13     CUST577    Male   21           Beauty   
571             572  2023-04-20     CUST572    Male   31         Clothing   
..              ...         ...         ...     ...  ...              ...   
190             191  2023-10-18     CUST191    Male   64           Beauty   
43               44  2023-02-19     CUST044  Female   22         Clothing   
543             544  2023-12-23     CUST544  Female   27      Electronics   
988             989  2023-12-28     CUST989  Female   44      Electronics   
978             979  2023-01-02     CUST979  Female   19           Beauty   

     Quantity  Price per Unit  Total Amount  
945         4             500